### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by ChefMC** [skygamezmc/SlashHub-Velocity#4]
Just updated Velocity from 1.20.2 to 1.20.5, updated all plugins and SlashHub, but on startup error was thrown:

```
[06:47:08] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Can't create plugin slashhub
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingMethod]: NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.moandjiezana.toml.Toml.getBoolean(String)" is null
  at SlashHub.SlashHub(SlashHub.java:97)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating SlashHub
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_METHOD
1 error
======================
Full classname legend:
======================
SlashHub:             "me.skygamez.slashhub.SlashHub"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
    at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.moandjiezana.toml.Toml.getBoolean(String)" is null
    at me.skygamez.slashhub.SlashHub.LoadConfigVars(SlashHub.java:92) ~[?:?]
    at me.skygamez.slashhub.SlashHub.SlashHub(SlashHub.java:109) ~[?:?]
    at me.skygamez.slashhub.SlashHub$$FastClassByGuice$$1d5d243.GUICE$TRAMPOLINE(<generated>) ~[?:?]
    at me.skygamez.slashhub.SlashHub$$FastClassByGuice$$1d5d243.apply(<generated>) ~[?:?]
    at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-385.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
    ... 6 more
```

**Comment by skygamezmc** [comment]
This problem is fixable by regenerating your config
